import Img1 from '/images2/product/img-1.png'
import Img2 from '/images2/product/img-2.png'
import Img3 from '/images2/product/img-3.png'
import Img4 from '/images2/product/img-4.png'
import Img5 from '/images2/product/img-5.png'
import Img6 from '/images2/product/img-6.png'

export const productData = [
  {
    id: 1,
    image: Img1,
    isTrending: true,
    brand: 'Nike',
    name: 'Nike N012 Shoes',
    disc: 'Gray, Shoes',
    oldprice: 280,
    newprice: 260,
    colors: ['dark', 'light', 'primary'],
    specification: ['High Quality', 'Leather', 'All Sizes available', '3 Different Color'],
    services: ['10 Days Replacement', 'Cash on Delivery available'],
  },
  {
    id: 2,
    image: Img2,
    discount: 20,
    brand: 'Adidas',
    name: 'Adidas Running Shoes',
    disc: 'Black, Shoes',
    oldprice: 250,
    newprice: 240,
    colors: ['danger', 'dark', 'light'],
    specification: ['High Quality', 'Leather', 'All Sizes available', '3 Different Color'],
    services: ['10 Days Replacement', 'Cash on Delivery available'],
  },
  {
    id: 3,
    image: Img3,
    brand: 'Puma',
    name: 'Puma P103 Shoes',
    disc: 'Purple, Shoes',
    oldprice: 260,
    newprice: 250,
    colors: ['purple', 'light', 'dark'],
    specification: ['High Quality', 'Leather', 'All Sizes available', '3 Different Color'],
    services: ['10 Days Replacement', 'Cash on Delivery available'],
  },
  {
    id: 4,
    image: Img4,
    brand: '',
    name: 'Sports S120 Shoes',
    disc: 'Purple, Shoes',
    oldprice: 240,
    newprice: 230,
    colors: ['info', 'success'],
    specification: ['High Quality', 'Leather', 'All Sizes available', '3 Different Color'],
    services: ['10 Days Replacement', 'Cash on Delivery available'],
  },
  {
    id: 5,
    image: Img5,
    brand: 'Adidas',
    name: 'Adidas AB23 Shoes',
    disc: 'Blue, Shoes',
    oldprice: 250,
    newprice: 240,
    colors: ['dark', 'light', 'primary'],
    specification: ['High Quality', 'Leather', 'All Sizes available', '3 Different Color'],
    services: ['10 Days Replacement', 'Cash on Delivery available'],
  },
  {
    id: 6,
    image: Img6,
    discount: 20,
    brand: 'Nike',
    name: 'Nike N012 Shoes',
    disc: 'Gray, Shoes',
    oldprice: 270,
    newprice: 260,
    colors: ['dark', 'light'],
    specification: ['High Quality', 'Leather', 'All Sizes available', '3 Different Color'],
    services: ['10 Days Replacement', 'Cash on Delivery available'],
  },
]
export const courseItems = [
  {
    id: 1,
    title: 'Starting SEO as your Home Based Business',
    image: 'course-01.jpg',
    alt: 'Course Thumb',
    duration: '4 Weeks',
    level: 'Advanced',
    ratingAvarage: '4.9',
    ratingTotal: '8',
    currentPrice: '49.00',
    lessons: '18',
    students: '43',
    category: 'Management',
    type: 'Online + Onsite',
    excerpt:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
    excerpt2:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
    excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
    instructor: 'Edward Norton',
    language: 'English',
    certificate: true,
    features: [
      'Learn to use Python professionally, learning both Python 2 & Python 3!',
      'Build 6 beautiful real-world projects for your portfolio (not boring toy',
      'Understand the Theory behind Vue.js and use it in Real Projects',
    ],
  },
  {
    id: 2,
    title: 'The Complete Camtasia Course for Content Creators',
    image: 'course-02.jpg',
    alt: 'Course Thumb',
    duration: '7 Weeks',
    level: 'Beginner',
    ratingAvarage: '5.0',
    ratingTotal: '9',
    currentPrice: '39.00',
    lessons: '61',
    students: '55',
    category: 'Business',
    type: 'Online Only',
    excerpt:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
    excerpt2:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
    excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
    instructor: 'Jane Seymour',
    language: 'English',
    certificate: true,
    features: [
      'Learn to use Python professionally, learning both Python 2 & Python 3!',
      'Build 6 beautiful real-world projects for your portfolio (not boring toy',
      'Understand the Theory behind Vue.js and use it in Real Projects',
    ],
  },
  {
    id: 3,
    title: 'Building A Better World One Student At A Time',
    image: 'course-03.jpg',
    alt: 'Course Thumb',
    duration: '8 Weeks',
    level: 'All Levels',
    ratingAvarage: '4.8',
    ratingTotal: '5',
    currentPrice: '59.00',
    lessons: '15',
    students: '40',
    category: 'Economics',
    type: 'Online + Onsite',
    excerpt:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
    excerpt2:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
    excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
    instructor: 'Penelope Cruz',
    language: 'English',
    certificate: true,
    features: [
      'Learn to use Python professionally, learning both Python 2 & Python 3!',
      'Build 6 beautiful real-world projects for your portfolio (not boring toy',
      'Understand the Theory behind Vue.js and use it in Real Projects',
    ],
  },
  {
    id: 4,
    title: 'Java Programming Masterclass for Software Developers',
    image: 'course-04.jpg',
    alt: 'Course Thumb',
    duration: '5 Weeks',
    level: 'Advanced',
    ratingAvarage: '4.8',
    ratingTotal: '9',
    currentPrice: '49.00',
    lessons: '25',
    students: '87',
    category: 'Software',
    type: 'Online Only',
    excerpt:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
    excerpt2:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
    excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
    instructor: 'John Travolta',
    language: 'English',
    certificate: true,
    features: [
      'Learn to use Python professionally, learning both Python 2 & Python 3!',
      'Build 6 beautiful real-world projects for your portfolio (not boring toy',
      'Understand the Theory behind Vue.js and use it in Real Projects',
    ],
  },
  {
    id: 5,
    title: 'Angular & NodeJS - The MEAN Stack Guide [2023 Edition]',
    image: 'course-05.jpg',
    alt: 'Course Thumb',
    duration: '12 Weeks',
    level: 'Beginner',
    ratingAvarage: '4.9',
    ratingTotal: '6',
    currentPrice: '29.00',
    lessons: '35',
    students: '74',
    category: 'Software',
    type: 'Online Only',
    excerpt:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
    excerpt2:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
    excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
    instructor: 'Edward Norton',
    language: 'English',
    certificate: true,
    features: [
      'Learn to use Python professionally, learning both Python 2 & Python 3!',
      'Build 6 beautiful real-world projects for your portfolio (not boring toy',
      'Understand the Theory behind Vue.js and use it in Real Projects',
    ],
  },
  {
    id: 6,
    title: 'The Complete React Developer Course (Hooks and Redux)',
    image: 'course-06.jpg',
    alt: 'Course Thumb',
    duration: '15 Weeks',
    level: 'Beginner',
    ratingAvarage: '4.7',
    ratingTotal: '8',
    currentPrice: '69.00',
    lessons: '10',
    students: '45',
    category: 'Software',
    type: 'Online + Onsite',
    excerpt:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
    excerpt2:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
    excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
    instructor: 'Jane Seymour',
    language: 'English',
    certificate: true,
    features: [
      'Learn to use Python professionally, learning both Python 2 & Python 3!',
      'Build 6 beautiful real-world projects for your portfolio (not boring toy',
      'Understand the Theory behind Vue.js and use it in Real Projects',
    ],
  },
  {
    id: 7,
    title: 'Build an app with ASPNET Core & Angular from Scratch Begainer',
    image: 'course-07.jpg',
    alt: 'Course Thumb',
    duration: '8 Weeks',
    level: 'All Levels',
    ratingAvarage: '4.8',
    ratingTotal: '4',
    currentPrice: '19.00',
    lessons: '15',
    students: '27',
    category: 'Software',
    type: 'Online Only',
    excerpt:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
    excerpt2:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
    excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
    instructor: 'Jane Seymour',
    language: 'English',
    certificate: true,
    features: [
      'Learn to use Python professionally, learning both Python 2 & Python 3!',
      'Build 6 beautiful real-world projects for your portfolio (not boring toy',
      'Understand the Theory behind Vue.js and use it in Real Projects',
    ],
  },
  {
    id: 8,
    title: 'Become a WordPress Developer: Unlocking Power with Code',
    image: 'course-08.jpg',
    alt: 'Course Thumb',
    duration: '14 Weeks',
    level: 'Beginner',
    ratingAvarage: '5.0',
    ratingTotal: '9',
    currentPrice: '49.00',
    lessons: '31',
    students: '90',
    category: 'Software',
    type: 'Online + Onsite',
    excerpt:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
    excerpt2:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
    excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
    instructor: 'Penelope Cruz',
    language: 'English',
    certificate: true,
    features: [
      'Learn to use Python professionally, learning both Python 2 & Python 3!',
      'Build 6 beautiful real-world projects for your portfolio (not boring toy',
      'Understand the Theory behind Vue.js and use it in Real Projects',
    ],
  },
  {
    id: 9,
    title: 'Build Responsive Real- World Websites with HTML and CSS',
    image: 'course-09.jpg',
    alt: 'Course Thumb',
    duration: '8 Weeks',
    level: 'All Levels',
    ratingAvarage: '4.9',
    ratingTotal: '7',
    currentPrice: '69.00',
    lessons: '29',
    students: '14',
    category: 'Development',
    type: 'Online + Onsite',
    excerpt:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
    excerpt2:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
    excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
    instructor: 'John Travolta',
    language: 'English',
    certificate: true,
    features: [
      'Learn to use Python professionally, learning both Python 2 & Python 3!',
      'Build 6 beautiful real-world projects for your portfolio (not boring toy',
      'Understand the Theory behind Vue.js and use it in Real Projects',
    ],
  },
  {
    id: 10,
    title: 'Vue - The Complete Guide (w/ Router, Vuex, Composition API)',
    image: 'course-10.jpg',
    alt: 'Course Thumb',
    duration: '11 Weeks',
    level: 'Basic',
    ratingAvarage: '5.0',
    ratingTotal: '5',
    currentPrice: '59.00',
    lessons: '20',
    students: '86',
    category: 'Development',
    type: 'Online Only',
    excerpt:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
    excerpt2:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
    excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
    instructor: 'Edward Norton',
    language: 'English',
    certificate: true,
    features: [
      'Learn to use Python professionally, learning both Python 2 & Python 3!',
      'Build 6 beautiful real-world projects for your portfolio (not boring toy',
      'Understand the Theory behind Vue.js and use it in Real Projects',
    ],
  },
  {
    id: 11,
    title: 'Master Microservices with Spring Boot and Spring Cloud',
    image: 'course-11.jpg',
    alt: 'Course Thumb',
    duration: '12 Weeks',
    level: 'Advanced',
    ratingAvarage: '4.8',
    ratingTotal: '3',
    currentPrice: '49.00',
    lessons: '41',
    students: '74',
    category: 'Software',
    type: 'Online + Onsite',
    excerpt:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
    excerpt2:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
    excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
    instructor: 'Penelope Cruz',
    language: 'English',
    certificate: true,
    features: [
      'Learn to use Python professionally, learning both Python 2 & Python 3!',
      'Build 6 beautiful real-world projects for your portfolio (not boring toy',
      'Understand the Theory behind Vue.js and use it in Real Projects',
    ],
  },
  {
    id: 12,
    title: 'The Complete Angular Course: Beginner to Advanced',
    image: 'course-12.jpg',
    alt: 'Course Thumb',
    duration: '7 Weeks',
    level: 'Basic',
    ratingAvarage: '4.9',
    ratingTotal: '6',
    currentPrice: '19.00',
    lessons: '18',
    students: '47',
    category: 'Development',
    type: 'Online Only',
    excerpt:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
    excerpt2:
      'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
    excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
    instructor: 'John Travolta',
    language: 'English',
    certificate: true,
    features: [
      'Learn to use Python professionally, learning both Python 2 & Python 3!',
      'Build 6 beautiful real-world projects for your portfolio (not boring toy',
      'Understand the Theory behind Vue.js and use it in Real Projects',
    ],
  },
]
export const colors = [
  { title: 'Black', color: 'dark' },
  { title: 'White', color: 'white' },
  { title: 'Gray', color: 'secondary' },
  { title: 'Blue', color: 'primary' },
  { title: 'Green', color: 'success' },
  { title: 'Red', color: 'danger' },
  { title: 'Yellow', color: 'warning' },
  { title: 'Purple', color: 'purple' },
]

export const discounts = [
  '50% or more',
  '40% or more',
  '30% or more',
  '20% or more',
  '10% or more',
  'Less than 10%',
]

export const customRating = [4, 3, 2, 1]

export const footwear = ['Formal Shoes', 'Sports Shoes', 'casual Shoes', 'Sandals', 'Slippers']
