export default {
  data() {
    return {
      courseItems: [
        {
          id: 1,
          title: 'Enquete sur le situation economique du payes',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '4 Weeks',
          level: 'Advanced',
          ratingAvarage: '4.9',
          ratingTotal: '8',
          currentPrice: '49.00',
          lessons: '18',
          students: '43',
          category: 'Management',
          type: 'Online + Onsite',
          excerpt:
            "Cette enquête vise à évaluer la situation économique actuelle du pays à travers la perception et l’expérience directe des citoyens. Elle a pour objectif de recueillir des données sur les revenus, l’emploi, le coût de la vie, l'accès aux biens et services de base, ainsi que sur les difficultés économiques rencontrées par les ménages.Les informations collectées permettront aux décideurs publics, aux chercheurs et aux acteurs économiques de mieux comprendre les réalités du terrain, de suivre l’évolution des conditions économiques, et d’orienter les politiques économiques et sociales en conséquence.",
          excerpt2:
            "Cette enquête vise à évaluer la situation économique actuelle du pays à travers la perception et l’expérience directe des citoyens. Elle a pour objectif de recueillir des données sur les revenus, l’emploi, le coût de la vie, l'accès aux biens et services de base, ainsi que sur les difficultés économiques rencontrées par les ménages.Les informations collectées permettront aux décideurs publics, aux chercheurs et aux acteurs économiques de mieux comprendre les réalités du terrain, de suivre l’évolution des conditions économiques, et d’orienter les politiques économiques et sociales en conséquence.",
          excerpt3:
            "Cette enquête vise à évaluer la situation économique actuelle du pays à travers la perception et l’expérience directe des citoyens. Elle a pour objectif de recueillir des données sur les revenus, l’emploi, le coût de la vie, l'accès aux biens et services de base, ainsi que sur les difficultés économiques rencontrées par les ménages.Les informations collectées permettront aux décideurs publics, aux chercheurs et aux acteurs économiques de mieux comprendre les réalités du terrain, de suivre l’évolution des conditions économiques, et d’orienter les politiques économiques et sociales en conséquence.",
          instructor: 'Edward Norton',
          language: 'English',
          certificate: true,
          features: [
            'Learn to use Python professionally, learning both Python 2 & Python 3!',
            'Build 6 beautiful real-world projects for your portfolio (not boring toy',
            'Understand the Theory behind Vue.js and use it in Real Projects',
          ],
        },
        {
          id: 2,
          title: 'Enquete sur le situation de santé du payes',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '7 Weeks',
          level: 'Beginner',
          ratingAvarage: '5.0',
          ratingTotal: '9',
          currentPrice: '39.00',
          lessons: '61',
          students: '55',
          category: 'Business',
          type: 'Online Only',
          excerpt:
            "Cette enquête vise à évaluer la situation économique actuelle du pays à travers la perception et l’expérience directe des citoyens. Elle a pour objectif de recueillir des données sur les revenus, l’emploi, le coût de la vie, l'accès aux biens et services de base, ainsi que sur les difficultés économiques rencontrées par les ménages.Les informations collectées permettront aux décideurs publics, aux chercheurs et aux acteurs économiques de mieux comprendre les réalités du terrain, de suivre l’évolution des conditions économiques, et d’orienter les politiques économiques et sociales en conséquence.",
          excerpt2:
            "Cette enquête vise à évaluer la situation économique actuelle du pays à travers la perception et l’expérience directe des citoyens. Elle a pour objectif de recueillir des données sur les revenus, l’emploi, le coût de la vie, l'accès aux biens et services de base, ainsi que sur les difficultés économiques rencontrées par les ménages.Les informations collectées permettront aux décideurs publics, aux chercheurs et aux acteurs économiques de mieux comprendre les réalités du terrain, de suivre l’évolution des conditions économiques, et d’orienter les politiques économiques et sociales en conséquence.",
          excerpt3:
            "Cette enquête vise à évaluer la situation économique actuelle du pays à travers la perception et l’expérience directe des citoyens. Elle a pour objectif de recueillir des données sur les revenus, l’emploi, le coût de la vie, l'accès aux biens et services de base, ainsi que sur les difficultés économiques rencontrées par les ménages.Les informations collectées permettront aux décideurs publics, aux chercheurs et aux acteurs économiques de mieux comprendre les réalités du terrain, de suivre l’évolution des conditions économiques, et d’orienter les politiques économiques et sociales en conséquence.",
          instructor: 'Jane Seymour',
          language: 'English',
          certificate: true,
          features: [
            'Learn to use Python professionally, learning both Python 2 & Python 3!',
            'Build 6 beautiful real-world projects for your portfolio (not boring toy',
            'Understand the Theory behind Vue.js and use it in Real Projects',
          ],
        },
        {
          id: 3,
          title: 'Enquete sur le situation du chommage du payes',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '8 Weeks',
          level: 'All Levels',
          ratingAvarage: '4.8',
          ratingTotal: '5',
          currentPrice: '59.00',
          lessons: '15',
          students: '40',
          category: 'Economics',
          type: 'Online + Onsite',
          excerpt:
            "Cette enquête vise à évaluer la situation économique actuelle du pays à travers la perception et l’expérience directe des citoyens. Elle a pour objectif de recueillir des données sur les revenus, l’emploi, le coût de la vie, l'accès aux biens et services de base, ainsi que sur les difficultés économiques rencontrées par les ménages.Les informations collectées permettront aux décideurs publics, aux chercheurs et aux acteurs économiques de mieux comprendre les réalités du terrain, de suivre l’évolution des conditions économiques, et d’orienter les politiques économiques et sociales en conséquence.",
          excerpt2:
            "Cette enquête vise à évaluer la situation économique actuelle du pays à travers la perception et l’expérience directe des citoyens. Elle a pour objectif de recueillir des données sur les revenus, l’emploi, le coût de la vie, l'accès aux biens et services de base, ainsi que sur les difficultés économiques rencontrées par les ménages.Les informations collectées permettront aux décideurs publics, aux chercheurs et aux acteurs économiques de mieux comprendre les réalités du terrain, de suivre l’évolution des conditions économiques, et d’orienter les politiques économiques et sociales en conséquence.",
          excerpt3:
            "Cette enquête vise à évaluer la situation économique actuelle du pays à travers la perception et l’expérience directe des citoyens. Elle a pour objectif de recueillir des données sur les revenus, l’emploi, le coût de la vie, l'accès aux biens et services de base, ainsi que sur les difficultés économiques rencontrées par les ménages.Les informations collectées permettront aux décideurs publics, aux chercheurs et aux acteurs économiques de mieux comprendre les réalités du terrain, de suivre l’évolution des conditions économiques, et d’orienter les politiques économiques et sociales en conséquence.",
          instructor: 'Penelope Cruz',
          language: 'English',
          certificate: true,
          features: [
            'Learn to use Python professionally, learning both Python 2 & Python 3!',
            'Build 6 beautiful real-world projects for your portfolio (not boring toy',
            'Understand the Theory behind Vue.js and use it in Real Projects',
          ],
        },
        {
          id: 4,
          title: 'Java Programming Masterclass for Software Developers',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '5 Weeks',
          level: 'Advanced',
          ratingAvarage: '4.8',
          ratingTotal: '9',
          currentPrice: '49.00',
          lessons: '25',
          students: '87',
          category: 'Software',
          type: 'Online Only',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
          excerpt2:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
          excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
          instructor: 'John Travolta',
          language: 'English',
          certificate: true,
          features: [
            'Learn to use Python professionally, learning both Python 2 & Python 3!',
            'Build 6 beautiful real-world projects for your portfolio (not boring toy',
            'Understand the Theory behind Vue.js and use it in Real Projects',
          ],
        },
        {
          id: 5,
          title: 'Angular & NodeJS - The MEAN Stack Guide [2023 Edition]',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '12 Weeks',
          level: 'Beginner',
          ratingAvarage: '4.9',
          ratingTotal: '6',
          currentPrice: '29.00',
          lessons: '35',
          students: '74',
          category: 'Software',
          type: 'Online Only',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
          excerpt2:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
          excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
          instructor: 'Edward Norton',
          language: 'English',
          certificate: true,
          features: [
            'Learn to use Python professionally, learning both Python 2 & Python 3!',
            'Build 6 beautiful real-world projects for your portfolio (not boring toy',
            'Understand the Theory behind Vue.js and use it in Real Projects',
          ],
        },
        {
          id: 6,
          title: 'The Complete React Developer Course (Hooks and Redux)',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '15 Weeks',
          level: 'Beginner',
          ratingAvarage: '4.7',
          ratingTotal: '8',
          currentPrice: '69.00',
          lessons: '10',
          students: '45',
          category: 'Software',
          type: 'Online + Onsite',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
          excerpt2:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
          excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
          instructor: 'Jane Seymour',
          language: 'English',
          certificate: true,
          features: [
            'Learn to use Python professionally, learning both Python 2 & Python 3!',
            'Build 6 beautiful real-world projects for your portfolio (not boring toy',
            'Understand the Theory behind Vue.js and use it in Real Projects',
          ],
        },
        {
          id: 7,
          title: 'Build an app with ASPNET Core & Angular from Scratch Begainer',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '8 Weeks',
          level: 'All Levels',
          ratingAvarage: '4.8',
          ratingTotal: '4',
          currentPrice: '19.00',
          lessons: '15',
          students: '27',
          category: 'Software',
          type: 'Online Only',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
          excerpt2:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
          excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
          instructor: 'Jane Seymour',
          language: 'English',
          certificate: true,
          features: [
            'Learn to use Python professionally, learning both Python 2 & Python 3!',
            'Build 6 beautiful real-world projects for your portfolio (not boring toy',
            'Understand the Theory behind Vue.js and use it in Real Projects',
          ],
        },
        {
          id: 8,
          title: 'Become a WordPress Developer: Unlocking Power with Code',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '14 Weeks',
          level: 'Beginner',
          ratingAvarage: '5.0',
          ratingTotal: '9',
          currentPrice: '49.00',
          lessons: '31',
          students: '90',
          category: 'Software',
          type: 'Online + Onsite',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
          excerpt2:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
          excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
          instructor: 'Penelope Cruz',
          language: 'English',
          certificate: true,
          features: [
            'Learn to use Python professionally, learning both Python 2 & Python 3!',
            'Build 6 beautiful real-world projects for your portfolio (not boring toy',
            'Understand the Theory behind Vue.js and use it in Real Projects',
          ],
        },
        {
          id: 9,
          title: 'Build Responsive Real- World Websites with HTML and CSS',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '8 Weeks',
          level: 'All Levels',
          ratingAvarage: '4.9',
          ratingTotal: '7',
          currentPrice: '69.00',
          lessons: '29',
          students: '14',
          category: 'Development',
          type: 'Online + Onsite',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
          excerpt2:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
          excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
          instructor: 'John Travolta',
          language: 'English',
          certificate: true,
          features: [
            'Learn to use Python professionally, learning both Python 2 & Python 3!',
            'Build 6 beautiful real-world projects for your portfolio (not boring toy',
            'Understand the Theory behind Vue.js and use it in Real Projects',
          ],
        },
        {
          id: 10,
          title: 'Vue - The Complete Guide (w/ Router, Vuex, Composition API)',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '11 Weeks',
          level: 'Basic',
          ratingAvarage: '5.0',
          ratingTotal: '5',
          currentPrice: '59.00',
          lessons: '20',
          students: '86',
          category: 'Development',
          type: 'Online Only',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
          excerpt2:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
          excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
          instructor: 'Edward Norton',
          language: 'English',
          certificate: true,
          features: [
            'Learn to use Python professionally, learning both Python 2 & Python 3!',
            'Build 6 beautiful real-world projects for your portfolio (not boring toy',
            'Understand the Theory behind Vue.js and use it in Real Projects',
          ],
        },
        {
          id: 11,
          title: 'Master Microservices with Spring Boot and Spring Cloud',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '12 Weeks',
          level: 'Advanced',
          ratingAvarage: '4.8',
          ratingTotal: '3',
          currentPrice: '49.00',
          lessons: '41',
          students: '74',
          category: 'Software',
          type: 'Online + Onsite',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
          excerpt2:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
          excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
          instructor: 'Penelope Cruz',
          language: 'English',
          certificate: true,
          features: [
            'Learn to use Python professionally, learning both Python 2 & Python 3!',
            'Build 6 beautiful real-world projects for your portfolio (not boring toy',
            'Understand the Theory behind Vue.js and use it in Real Projects',
          ],
        },
        {
          id: 12,
          title: 'The Complete Angular Course: Beginner to Advanced',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '7 Weeks',
          level: 'Basic',
          ratingAvarage: '4.9',
          ratingTotal: '6',
          currentPrice: '19.00',
          lessons: '18',
          students: '47',
          category: 'Development',
          type: 'Online Only',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
          excerpt2:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod tempor incidid unt labore dolore magna.',
          excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
          instructor: 'John Travolta',
          language: 'English',
          certificate: true,
          features: [
            'Learn to use Python professionally, learning both Python 2 & Python 3!',
            'Build 6 beautiful real-world projects for your portfolio (not boring toy',
            'Understand the Theory behind Vue.js and use it in Real Projects',
          ],
        },
      ],
      universityCourses: [
        {
          id: 1,
          title: 'Public Administration',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          ratingAvarage: '4.9',
          ratingTotal: '8',
          currentPrice: '49.00',
          category: 'Management',
          type: 'Onsite Only',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
        },
        {
          id: 2,
          title: 'Major in Economics',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          ratingAvarage: '5.0',
          ratingTotal: '9',
          currentPrice: '39.00',
          category: 'Economics',
          type: 'Online + Onsite',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
        },
        {
          id: 3,
          title: 'Business Studies',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          ratingAvarage: '4.8',
          ratingTotal: '5',
          currentPrice: '59.00',
          category: 'Business',
          type: 'Online Only',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
        },
      ],
      kitchenCourses: [
        {
          id: 1,
          title: 'Healthy Sushi Roll - Japanese Popular Cooking Class',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '35 hrs',
          level: 'Advanced',
          ratingAvarage: '4.9',
          currentPrice: '30',
          lessons: '18',
          students: '43',
          category: 'Cooking',
          excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
          features: [
            'Professional Japanese cooking from beginners to experts',
            'Will be able to cook authentic Italian recipes in their own kitchen',
            'Understand the HOW of cooking, before thinking of the WHAT to cook.',
          ],
        },
        {
          id: 2,
          title: 'Nutrition Kitchen - Basics of Cooking for Busy People',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '29 hrs',
          level: 'Beginner',
          ratingAvarage: '5.0',
          currentPrice: '40',
          lessons: '59',
          students: '67',
          category: 'Cooking',
          excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
          features: [
            'Prepare a huge variety of simple, delicious, healthy recipes.',
            'Professional Indian cooking from beginners to experts',
            'Serve delicious and healthy meals for your loved ones.',
          ],
        },
        {
          id: 3,
          title: 'Vegan Thai Cooking Classes Popular Vegan Recipes',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          duration: '14 hrs',
          level: 'Intermediate',
          ratingAvarage: '5.0',
          currentPrice: '50',
          lessons: '24',
          students: '80',
          category: 'Cooking',
          excerpt3: 'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor.',
          features: [
            'Cook much loved recipes like ravioli, pizza and pesto from scratch',
            'Cook better than restaurant Thai food at home',
            'Keep your food safe from harmful bacteria and disease.',
          ],
        },
      ],
      kindergartenCourses: [
        {
          id: 1,
          colorClass: 'bg-color-extra02',
          title: 'The Ultimate Drawing Course - Beginner to Advanced',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          currentPrice: '30',
          lessons: '18',
          students: '43',
          category: 'Drawing',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
        },
        {
          id: 2,
          colorClass: 'bg-color-secondary',
          title: 'Powerful Calming Techniques For Kids and Teens',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          currentPrice: '40',
          lessons: '59',
          students: '67',
          category: 'Techniques',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
        },
        {
          id: 3,
          colorClass: 'bg-color-primary',
          title: 'Parenting Skills to Raise Responsible Children',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          currentPrice: '50',
          lessons: '24',
          students: '80',
          category: 'Parenting',
          excerpt:
            'Lorem ipsum dolor sit amet consectur elit sed eiusmod ex tempor incididunt labore dolore magna.',
        },
      ],
      yogaCourses: [
        {
          id: 1,
          title: 'Yoga for Back Pain Relief',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          currentPrice: '30',
          lessons: '15',
          students: '31',
          category: 'Meditation',
        },
        {
          id: 2,
          title: 'Super Brain YOGA',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          currentPrice: '40',
          lessons: '18',
          students: '43',
          category: 'Power Yoga',
        },
        {
          id: 3,
          title: 'Chair Yoga for Seniors',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          currentPrice: '50',
          lessons: '35',
          students: '16',
          category: 'Pranayama',
        },
        {
          id: 4,
          title: 'Online Yoga for Beginners',
          image: 'sondage.webp',
          alt: 'Course Thumb',
          currentPrice: '60',
          lessons: '22',
          students: '56',
          category: 'Power Yoga',
        },
      ],
    }
  },
}
